<a href="https://colab.research.google.com/github/sebastian-jarosz/pandas_laboratory/blob/main/Sebastian_Jarosz_Pandas_Laboratorium_3_Zadania.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Author - Sebastian Jarosz
# Student Nr - 78797

import numpy as np
import pandas as pd

df_one = pd.read_csv('https://gist.githubusercontent.com/palles77/29cdaafd1f4eeabed8420433848c49e3/raw/72690b0a1333ddac01ca7b59bf4f671ac0a8ad35/employees10000.csv', index_col=False)

# Zadanie nr 1 - Wykonać wybrane 7 zadań z poniższej listy

print("Wypisać średnią dla kolumny ‘Age in Company(Years)’, których pierwsza litera nazwiska zaczyna się na ‘A’:")
print(df_one[df_one['Last Name'].str.startswith('A')]['Age in Company (Years)'].mean())

print('-------------------------')

print("Wypisać wartość średnią, odchylenie standardowe pensji wszystkich pracowników:")
print("Wartość średnia: " + str(df_one['Salary'].mean()))
print("Odchylenie standardowe: " + str(df_one['Salary'].std()))

print('-------------------------')

print("Wypisać średnią płacę dla kobiet:")
print(df_one[df_one['Gender'] == 'F']['Salary'].mean())

print('-------------------------')

print("Wypisać średnią płacę dla mężczyzn:")
print(df_one[df_one['Gender'] == 'M']['Salary'].mean())

print('-------------------------')

print("Wypisać wszystkie unikalne imiona dla mężczyzn. ")
print(df_one[df_one['Gender'] == 'M']['First Name'].unique())

print('-------------------------')

print("Wypisać wszystkie unikalne nazwiska dla kobiet. ")
print(df_one[df_one['Gender'] == 'F']['Last Name'].unique())

print('-------------------------')

print("Wypisać, ilu mężczyzn ma email na gmail.com. ")
print(len(df_one.loc[(df_one['Gender'] == 'M') & (df_one['E Mail'].str.endswith('gmail.com'))]))


# Zadanie nr 2 - Połączyć dane z punktu 1 z plikiem poniższym według numeru pracownika. Dla połączonych danych wykonać wybrane 4 z 10 następujących zadania

df_two = pd.read_csv('https://gist.githubusercontent.com/palles77/518c8b04c73d464db5453efd2c2d7925/raw/1951fa9311cd2c13397dbd8a2d4334d61953a8e5/hra10000.csv', index_col=False)

df_joined = pd.merge(df_one, df_two, left_on='Emp ID', right_on='EmployeeNumber')

print('-------------------------')

print("Ilu pracowników pracuje w poszczególnych departamentach (grupowanie)")
print(df_joined.groupby(['Department']).size())

print('-------------------------')

print("Ilość pracowników w poszczególnych dziedzinach wykształcenia (grupowanie)")
print(df_joined.groupby(['EducationField']).size())
print(df_joined.groupby(['Department']).size())

print('-------------------------')

print("Imiona wszystkich kobiet pracujących w dziale ‘Research & Development’.")
print(df_joined.loc[(df_one['Gender'] == 'F') & (df_joined['Department'] == 'Research & Development')]['First Name'])

print('-------------------------')

print("Ilość mężczyzn na stanowisku ‘Manager’.")
print(len(df_joined.loc[(df_one['Gender'] == 'M') & (df_joined['JobRole'] == 'Manager')]))

Wypisać średnią dla kolumny ‘Age in Company(Years)’, których pierwsza litera nazwiska zaczyna się na ‘A’:
9.703497109826591
-------------------------
Wypisać wartość średnią, odchylenie standardowe pensji wszystkich pracowników:
Wartość średnia: 119169.4497
Odchylenie standardowe: 45891.78292688886
-------------------------
Wypisać średnią płacę dla kobiet:
119618.05457853245
-------------------------
Wypisać średnią płacę dla mężczyzn:
118730.25549178706
-------------------------
Wypisać wszystkie unikalne imiona dla mężczyzn.
['Milan' 'Elmer' 'Rhett' ... 'Sandy' 'Eugenio' 'Frederick']
-------------------------
Wypisać wszystkie unikalne nazwiska dla kobiet.
['Bumgarner' 'Rojo' 'Forest' ... 'Aiken' 'Gupta' 'Weigand']
-------------------------
Wypisać, ilu mężczyzn ma email na gmail.com.
1582
-------------------------
Ilu pracowników pracuje w poszczególnych departamentach (grupowanie)
Department
Hardware                  1561
Human Resources           1669
Research & Development    1636
Sales                     1694
Software                  1747
Support                   1693
dtype: int64
-------------------------
Ilość pracowników w poszczególnych dziedzinach wykształcenia (grupowanie)
EducationField
Human Resources     1687
Life Sciences       1618
Marketing           1685
Medical             1701
Other               1667
Technical Degree    1642
dtype: int64
Department
Hardware                  1561
Human Resources           1669
Research & Development    1636
Sales                     1694
Software                  1747
Support                   1693
dtype: int64
-------------------------
Imiona wszystkich kobiet pracujących w dziale ‘Research & Development’.
13        Ardath
16       Avelina
38        Judith
39       Laureen
59          Lisa
          ...
9955        Elna
9958       Shila
9959         Meg
9974    Criselda
9976      Tiesha
Name: First Name, Length: 824, dtype: object
-------------------------
Ilość mężczyzn na stanowisku ‘Manager’.
508